package com.openintl.ws.product_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2022-04-20T08:45:26.920-05:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://ws.openintl.com/product-service", name = "Product")
@XmlSeeAlso({com.openintl.ws.product_service.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Product {

    @WebMethod
    @WebResult(name = "productResponse", targetNamespace = "http://ws.openintl.com/product-service/types", partName = "response")
    public com.openintl.ws.product_service.types.ProductResponse getProductDetails(
        @WebParam(partName = "request", name = "productRequest", targetNamespace = "http://ws.openintl.com/product-service/types")
        com.openintl.ws.product_service.types.ProductRequest request
    ) throws ErrorMessage;
}
